import { crawlerDashboardCopy as copy } from "@/config/copy/crawler-dashboard";
import type { CrawlerAnalyticsResponse } from "@/lib/crawler-analytics/types";

type Props = { submissions?: CrawlerAnalyticsResponse["scanSubmissions"] };
type AvailableSubmissions = Extract<NonNullable<CrawlerAnalyticsResponse["scanSubmissions"]>, { available?: true }>;
const cellClass = "border-b border-hairline px-3 py-3";

function errorLabel(code: string): string {
  return `${copy.submissions.errorCodes[code as keyof typeof copy.submissions.errorCodes] ?? copy.submissions.unknownReason}（${code}）`;
}

function SubmissionDomains({ domains }: { domains?: AvailableSubmissions["domains"] }) {
  if (!domains) return <section aria-labelledby="free-report-domains-title" role="status" className="border-t border-hairline pt-5"><h3 id="free-report-domains-title" className="text-base font-semibold">{copy.submissions.domains.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy.submissions.domains.notEnabled}</p></section>;
  if (!domains.available) return <section aria-labelledby="free-report-domains-title" role="status" className="border-t border-hairline pt-5"><h3 id="free-report-domains-title" className="text-base font-semibold">{copy.submissions.domains.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy.submissions.domains.unavailable}</p></section>;
  if (!domains.trackingStartedAt) return <section aria-labelledby="free-report-domains-title" role="status" className="border-t border-hairline pt-5"><h3 id="free-report-domains-title" className="text-base font-semibold">{copy.submissions.domains.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy.submissions.domains.waiting}</p></section>;
  if (domains.requestedWindowComplete && domains.summary.requests === 0) return <section aria-labelledby="free-report-domains-title" role="status" className="border-t border-hairline pt-5"><h3 id="free-report-domains-title" className="text-base font-semibold">{copy.submissions.domains.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy.submissions.domains.empty}</p></section>;
  return <section aria-labelledby="free-report-domains-title" className="border-t border-hairline pt-5"><h3 id="free-report-domains-title" className="text-base font-semibold">{copy.submissions.domains.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy.submissions.domains.disclaimer}</p>{!domains.requestedWindowComplete ? <p className="mt-1 text-sm leading-6 text-muted-foreground">{copy.submissions.domains.partialWindow} {domains.trackingStartedAt}</p> : null}{domains.omittedRequests > 0 ? <p className="mt-1 text-sm leading-6 text-muted-foreground">{copy.submissions.domains.omitted}：{domains.omittedRequests}</p> : null}<div className="mt-4 overflow-x-auto"><table aria-label={copy.submissions.domains.title} className="w-full min-w-[560px] text-left text-sm"><thead className="text-muted-foreground"><tr><th className={cellClass}>{copy.submissions.domains.domain}</th><th className={cellClass}>{copy.submissions.requests}</th><th className={cellClass}>{copy.submissions.accepted}</th><th className={cellClass}>{copy.submissions.failed}</th><th className={cellClass}>{copy.submissions.other}</th></tr></thead><tbody>{domains.rows.map((row) => <tr key={row.domain || "unknown"}><td className={cellClass}><span className="block max-w-lg break-all">{row.domain || copy.submissions.domains.unknown}</span></td><td className={cellClass}>{row.requests}</td><td className={cellClass}>{row.accepted}</td><td className={cellClass}>{row.failed}</td><td className={cellClass}>{row.other}</td></tr>)}</tbody></table></div></section>;
}

export function FreeReportSubmissions({ submissions }: Props) {
  if (!submissions) return <section aria-labelledby="free-report-submissions-title" role="status" className="border border-hairline bg-surface-paper-elevated p-6"><h2 id="free-report-submissions-title" className="text-lg font-semibold">{copy.submissions.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy.submissions.notEnabled}</p></section>;
  if (!submissions.available) return <section aria-labelledby="free-report-submissions-title" role="status" className="border border-hairline bg-surface-paper-elevated p-6"><h2 id="free-report-submissions-title" className="text-lg font-semibold">{copy.submissions.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy.submissions.unavailable}</p></section>;
  if (!submissions.trackingStartedAt) return <section aria-labelledby="free-report-submissions-title" role="status" className="border border-hairline bg-surface-paper-elevated p-6"><h2 id="free-report-submissions-title" className="text-lg font-semibold">{copy.submissions.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy.submissions.waiting}</p></section>;
  if (submissions.requestedWindowComplete && submissions.summary.requests === 0) return <section aria-labelledby="free-report-submissions-title" role="status" className="border border-hairline bg-surface-paper-elevated p-6"><h2 id="free-report-submissions-title" className="text-lg font-semibold">{copy.submissions.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy.submissions.disclaimer}</p><p className="mt-3 text-sm leading-6 text-muted-foreground">{copy.submissions.empty}</p><SubmissionDomains domains={submissions.domains} /></section>;
  const cards = [[copy.submissions.requests, submissions.summary.requests], [copy.submissions.accepted, submissions.summary.accepted], [copy.submissions.failed, submissions.summary.failed]] as const;
  return <section aria-labelledby="free-report-submissions-title" className="space-y-5 border-t border-hairline pt-5">
    <div><h2 id="free-report-submissions-title" className="text-lg font-semibold">{copy.submissions.title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{copy.submissions.disclaimer}</p>{!submissions.requestedWindowComplete ? <p className="mt-1 text-sm leading-6 text-muted-foreground">{copy.submissions.partialWindow} {submissions.trackingStartedAt}</p> : null}</div>
    <div className="grid grid-cols-1 gap-px border border-hairline bg-hairline sm:grid-cols-3">{cards.map(([label, value]) => <section key={label} className="bg-surface-paper p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-3 text-3xl font-semibold">{value}</p></section>)}</div>
    {submissions.summary.other > 0 ? <p className="border border-hairline bg-surface-paper-elevated p-4 text-sm leading-6 text-muted-foreground">{copy.submissions.other}：{submissions.summary.other}。{copy.submissions.otherHelp}</p> : null}
    {submissions.summary.transportErrors > 0 ? <p className="text-sm leading-6 text-muted-foreground">{copy.submissions.transportErrors}：{submissions.summary.transportErrors}。{copy.submissions.transportErrorsHelp}</p> : null}
    <div className="grid grid-cols-1 gap-8 lg:grid-cols-2">
      <div className="overflow-x-auto"><h3 className="text-base font-semibold">{copy.submissions.statuses}</h3><table aria-label={copy.submissions.statuses} className="mt-4 w-full min-w-[280px] text-left text-sm"><thead className="text-muted-foreground"><tr><th className={cellClass}>{copy.status}</th><th className={cellClass}>{copy.requests}</th></tr></thead><tbody>{submissions.statuses.map((row) => <tr key={row.status}><td className={cellClass}>{row.status === 0 ? copy.submissions.noHttpStatus : row.status}</td><td className={cellClass}>{row.requests}</td></tr>)}</tbody></table></div>
      <div className="overflow-x-auto"><h3 className="text-base font-semibold">{copy.submissions.errors}</h3><table aria-label={copy.submissions.errors} className="mt-4 w-full min-w-[280px] text-left text-sm"><thead className="text-muted-foreground"><tr><th className={cellClass}>{copy.status}</th><th className={cellClass}>{copy.submissions.reason}</th><th className={cellClass}>{copy.requests}</th></tr></thead><tbody>{submissions.errors.map((row) => <tr key={`${row.status}:${row.code}`}><td className={cellClass}>{row.status === 0 ? copy.submissions.noHttpStatus : row.status}</td><td className={cellClass}>{errorLabel(row.code)}</td><td className={cellClass}>{row.requests}</td></tr>)}</tbody></table></div>
    </div>
    <SubmissionDomains domains={submissions.domains} />
  </section>;
}
