services:
  personal-website:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENABLE_ADMIN: "true"
        ADMIN_TOKEN: "${ADMIN_TOKEN}"
        ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
    container_name: personal-website
    ports:
      - "3100:3100"
    environment:
      - ENABLE_ADMIN=true
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: unless-stopped
