import { defineConfig } from "vitest/config";
import path from "node:path";

export default defineConfig({
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "."),
    },
  },
  test: {
    environment: "node",
    include: ["tests/**/*.test.ts", "tests/**/*.test.tsx"],
    globals: true,
    testTimeout: 30000,
    setupFiles: ["./tests/helpers/setup.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html"],
      include: [
        "lib/photo-auth.ts",
        "lib/github-photo.ts",
        "lib/admin-guard.ts",
        "lib/structured-data.ts",
        "lib/youtube.ts",
        "lib/devto.ts",
        "lib/github/contributions.ts",
        "lib/mdx/mdx.ts",
        "components/PageBlocks.tsx",
        "components/PhotographyGallery.tsx",
        "components/PhotoPinModal.tsx",
        "components/admin/AdminSidebar.tsx",
        "components/admin/AdminEditor.tsx",
        "components/Navbar.tsx",
        "components/Footer.tsx",
        "components/ThemeToggle.tsx",
        "components/ThemeProvider.tsx",
        "components/ShareButton.tsx",
        "components/Breadcrumbs.tsx",
        "components/BrandGlyphs.tsx",
        "components/Typewriter.tsx",
        "components/ErrorBoundary.tsx",
        "components/articles/ArticleCard.tsx",
        "components/articles/ArticlesBrowser.tsx",
        "components/articles/ShareLinks.tsx",
        "components/projects/ProjectCard.tsx",
        "components/projects/FeaturedProjectsTicker.tsx",
        "components/sections/Hero.tsx",
        "components/sections/HeroShowcaseSection.tsx",
        "components/sections/About.tsx",
        "components/sections/Projects.tsx",
        "components/sections/ProjectsClient.tsx",
        "components/sections/Articles.tsx",
        "components/sections/Education.tsx",
        "components/sections/Experience.tsx",
        "components/sections/Certifications.tsx",
        "components/sections/Content.tsx",
        "components/sections/ContentMedia.tsx",
        "components/sections/Publications.tsx",
        "components/sections/YouTube.tsx",
        "components/mdx/MdxRenderer.tsx",
        "components/mdx/MdxComponents.tsx",
        "components/mdx/CodeBlock.tsx",
        "components/mdx/Callout.tsx",
        "components/ui/Skeleton.tsx",
        "components/ui/Tooltip.tsx",
        "components/ui/CopyButton.tsx",
        "components/ui/PdfEmbed.tsx",
        "app/api/auth/photo-session/route.ts",
        "app/api/photo/[id]/route.ts",
        "app/api/admin/save/route.ts",
        "app/api/admin/photography/route.ts",
        "app/api/admin/[key]/route.ts",
        "app/api/github-contributions/route.ts",
        "app/api/views/[slug]/route.ts",
      ],
      exclude: ["node_modules/", "tests/", "*.config.*", "types/"],
      thresholds: {
        statements: 85,
        branches: 75,
        functions: 88,
        lines: 88,
      },
    },
  },
});
