export const adminCopy = {
  common: {
    brand: "fengc",
    product: "Admin Workbench",
    backToSite: "返回网站",
    saveToGitHub: "保存到 GitHub",
    saving: "保存中...",
    loading: "加载中...",
    empty: "暂无内容",
  },
  sidebar: {
    general: "General",
    content: "Content",
    dashboard: "Dashboard",
    site: "Site Settings",
    navbar: "Navbar",
    about: "About",
    theme: "Theme",
    photography: "Photography",
    pages: "Custom Pages",
    autoSaveHint: "保存后会自动推送到 GitHub",
  },
  login: {
    title: "管理后台",
    description: "请输入管理员密码",
    panelTitle: "访问验证",
    passwordLabel: "密码",
    passwordPlaceholder: "输入管理员密码",
    submit: "进入管理后台",
    verifying: "验证中...",
    loading: "加载中...",
    tokenHint: "也可以使用访问令牌直接登录。",
    errors: {
      loginFailed: "登录失败",
      network: "网络错误，请重试",
    },
  },
  dashboard: {
    title: "管理后台",
    description: "管理个人网站内容、导航、主题与发布资料。保存后会自动推送到 GitHub。",
    cards: {
      site: {
        label: "站点设置",
        description: "修改站点名称、标题、简介和社交链接。",
      },
      navbar: {
        label: "导航栏",
        description: "编辑导航菜单、下拉菜单和 CTA 按钮。",
      },
      about: {
        label: "关于我",
        description: "编辑个人简介、技术栈和个人故事。",
      },
      theme: {
        label: "主题配色",
        description: "选择强调色、明暗模式和默认主题。",
      },
      photography: {
        label: "摄影作品",
        description: "管理摄影项目、上传照片并设置公开或私密。",
      },
      pages: {
        label: "自定义页面",
        description: "创建和管理自定义页面，自由组织内容块。",
      },
    },
    quickLinks: {
      title: "快捷链接",
      photography: "摄影主页",
      website: "网站首页",
      github: "GitHub 仓库",
    },
  },
  editor: {
    backToDashboard: "返回控制台",
    loadFailed: "加载失败",
    invalidPayload: "配置数据格式无效",
    saveFailed: "保存失败",
    requestFailed: "请求失败",
    savedAndDeployed: "已保存并部署",
    savedDeployFailed: "已保存，但自动部署失败",
    deploying: "已保存，正在部署到 Vercel...",
    ci: {
      notFound: "CI：暂未找到工作流运行",
      queued: "排队中",
      running: "运行中",
      passed: "已通过",
      failed: "失败",
    },
  },
  theme: {
    title: "主题",
    description: "选择强调色、默认显示模式和访客主题控制方式。",
    displayModeTitle: "显示模式",
    lightMode: "浅色",
    darkMode: "深色",
    allowToggle: "允许访客切换主题",
    respectSystemPreference: "跟随系统偏好",
    accentColorTitle: "强调色",
    presetLabels: {
      indigo: "Indigo",
      emerald: "Emerald",
      rose: "Rose",
      amber: "Amber",
      cyan: "Cyan",
      violet: "Violet",
      sky: "Sky",
    },
  },
  site: {
    title: "站点设置",
    description: "维护站点身份、公开社交链接和首页板块开关。",
    identityTitle: "基本信息",
    identityDescription: "这些字段会进入公开页面、SEO、AI-readable 资料和分享卡片。",
    nameLabel: "站点名称",
    titleLabel: "头衔",
    taglineLabel: "标语",
    locationLabel: "位置",
    baseUrlLabel: "基础 URL",
    socialsTitle: "社交链接",
    socialsDescription: "公开联系方式和内容入口。链接会被首页、links 页和 AI-readable 层引用。",
    socialKeyLabel: "渠道",
    socialLabelPlaceholder: "显示名称",
    socialHrefPlaceholder: "链接 URL",
    sectionsTitle: "页面板块开关",
    sectionsDescription: "控制首页主要模块是否显示；关闭后不应影响对应详情页或 crawler inventory。",
    noSocials: "暂无社交链接。",
  },
  navbar: {
    title: "导航栏",
    description: "编辑顶部导航菜单项、下拉菜单和 CTA 按钮。",
    logoTitle: "品牌入口",
    logoDescription: "控制左上角品牌文字与返回首页链接。",
    logoLabel: "显示文字",
    logoHref: "链接到",
    menuTitle: "菜单项",
    menuDescription: "这些项目会生成公共站点导航；隐藏项目不会从公开页面删除对应内容。",
    itemLabel: "名称",
    itemHref: "链接",
    childLabel: "子菜单名称",
    childHref: "子菜单链接",
    showItem: "显示",
    addItem: "添加菜单项",
    addChild: "添加子菜单",
    removeItem: "删除菜单项",
    removeChild: "删除子菜单",
    ctaTitle: "CTA 按钮",
    ctaDescription: "配置导航右侧主行动按钮。",
    ctaLabel: "按钮文字",
    ctaHref: "按钮链接",
    noItems: "暂无菜单项。",
  },
  about: {
    title: "关于我",
    description: "维护个人身份、双语简介、技术栈和关于页 CTA。",
    profileTitle: "个人身份",
    profileDescription: "这些字段会进入首页、关于页和 AI-readable 身份资料。",
    displayNameLabel: "显示名称",
    handleLabel: "GitHub ID",
    avatarLabel: "头像 URL",
    localizedTitle: "本地化简介",
    localizedDescription: "按语言维护公开简介、README 段落和行动按钮。",
    roleLineLabel: "角色标签",
    readmeTitle: "README 段落",
    addParagraph: "添加段落",
    removeParagraph: "删除段落",
    afterTechLabel: "技术栈后简介",
    techTitle: "技术栈",
    techDescription: "用于首页、关于页和结构化资料的技能标签。",
    addTechPlaceholder: "添加技术...",
    removeTech: "删除技术",
    ctaTitle: "CTA 按钮",
    primaryLabel: "主按钮文字",
    primaryHref: "主按钮链接",
    secondaryLabel: "次按钮文字",
    secondaryHref: "次按钮链接",
    localeLabels: {
      zh: "中文",
      en: "English",
    },
  },
  pages: {
    title: "自定义页面",
    description: "创建和管理自定义页面，自由组织面向访客和 crawler 的结构化内容。",
    pageTitleLabel: "页面标题",
    slugLabel: "Slug",
    slugPrefix: "/page/",
    descriptionLabel: "页面描述",
    preview: "预览",
    removePage: "删除页面",
    addPage: "添加新页面",
    emptyTitle: "暂无自定义页面",
    emptyDescription: "添加页面后会自动进入 `/page/[slug]` 路由和 sitemap inventory。",
    blocksTitle: "页面区块",
    addBlock: "添加区块",
    removeBlock: "删除区块",
    blockTitleLabel: "区块标题",
    blockTypeLabel: "区块类型",
    blockTypes: {
      hero: "Hero 标题区",
      text: "文本区",
      gallery: "图片画廊",
      cards: "卡片列表",
      contact: "联系方式",
    },
    heroHeadline: "大标题",
    heroSubheadline: "副标题",
    heroCtaText: "按钮文字",
    textPlaceholder: "输入文本内容...",
    galleryNote: "图片画廊：当前由配置内容渲染，后续可扩展为资产选择器。",
    cardsTitle: "卡片",
    cardTitle: "卡片标题",
    cardDescription: "描述",
    addCard: "添加卡片",
    removeCard: "删除卡片",
    contactNote: "联系方式区块会读取站点配置中的公开社交链接。",
    newPageTitle: "新页面",
    newPageSlug: "new-page",
    newBlockTitle: "新区块",
    newTextContent: "在此输入内容...",
    newHeroTitle: "欢迎",
    newHeroHeadline: "标题",
    newHeroSubheadline: "副标题",
    newCardTitle: "新卡片",
    newCardDescription: "卡片描述",
  },
  photography: {
    title: "照片管理后台",
    description: "编辑摄影项目与照片，保存后自动推送到 GitHub。",
    backToPublic: "返回摄影页面",
    projectList: "项目列表",
    photoCountSuffix: "张照片",
    projectInfoTitle: "项目信息",
    projectInfoDescription: "这些字段会影响公开摄影索引和相册详情页。",
    projectTitleLabel: "项目名称",
    projectDescriptionLabel: "项目描述",
    uploadPhotos: "上传照片",
    addManualPhoto: "手动添加条目",
    pendingUploads: "待上传",
    pendingSuffix: "张",
    emptyProjectTitle: "暂无照片",
    emptyProjectDescription: "选择上传照片，或先手动添加一个占位条目。",
    selectProject: "选择一个项目开始编辑。",
    newPhotoTitle: "新照片",
    photoTitlePlaceholder: "照片标题",
    photoDescriptionPlaceholder: "照片描述",
    datePlaceholder: "YYYY-MM",
    widthLabel: "宽",
    heightLabel: "高",
    makePublic: "设为公开",
    makePrivate: "设为私密",
    moveUp: "上移",
    moveDown: "下移",
    deletePhoto: "删除照片",
    noPreview: "无预览",
    messages: {
      loadFailed: "加载失败",
      saveFailed: "保存失败",
      saveFallback: "已保存",
    },
  },
};
