import type { CrawlerAnalyticsErrorCode } from "@/lib/crawler-analytics/types";

export const crawlerDashboardCopy = {
  title: "AI 爬虫检测",
  description: "区分已识别 AI 爬虫、Open GEO 自测和其他自动化请求。",
  source: "Cloudflare GraphQL Analytics",
  backToSite: "返回网站",
  ranges: { "24h": "24h", "7d": "7d", "30d": "30d" },
  automationTotal: "自动化请求",
  totalRequestBaseline: "总请求基线",
  share: "占比",
  queryWindow: "查询窗口",
  lastRefresh: "最后刷新",
  categories: {
    identified_ai_crawler: "已识别 AI 爬虫",
    open_geo_self_test: "Open GEO 自测",
    other_automation: "其他自动化",
  },
  trend: "自动化请求趋势",
  trendData: "自动化请求趋势数据",
  agents: "爬虫与 User-Agent",
  paths: "热门路径",
  statuses: "状态码分布",
  generatedAt: "生成时间",
  declaredUserAgent: "声明的 User-Agent",
  category: "分类",
  requests: "请求数",
  path: "路径",
  status: "状态码",
  total: "合计",
  emptyTrend: "所选时间内没有可绘制的自动化趋势。",
  empty: "所选时间内未识别到自动化流量；这不代表不存在未声明身份的爬虫。",
  sampled: "Cloudflare 对该时间范围使用了采样，显示数量为估算值。",
  identityDisclaimer: "分类依据请求声明的 User-Agent，不代表运营方身份已经验证。",
  errors: {
    configuration_missing: "爬虫检测尚未配置 Cloudflare 只读凭据。",
    cloudflare_auth_invalid: "Cloudflare Token 无效或已经过期。",
    cloudflare_permission_denied: "Cloudflare Token 缺少目标 Zone 的 Analytics Read 权限。",
    cloudflare_rate_limited: "Cloudflare 暂时限制了查询，请稍后再试。",
    cloudflare_unavailable: "Cloudflare Analytics 当前不可用。",
    unsupported_dataset: "当前 Cloudflare 套餐或 Zone 不支持所需分析维度。",
    result_truncated: "结果超过当前安全查询上限，未展示不完整统计。",
    invalid_range: "时间范围无效，请选择 24 小时、7 天或 30 天。",
  } satisfies Record<CrawlerAnalyticsErrorCode, string>,
} as const;
