import type { CrawlerAnalyticsErrorCode } from "@/lib/crawler-analytics/types";

export const crawlerDashboardCopy = {
  title: "访问检测",
  views: {
    human: { label: "人类访问", title: "人类访问", description: "查看真实浏览器页面请求、热门页面、访问时段和客户端分布。" },
    machines: { label: "机器访问", title: "机器访问", description: "查看声明的 AI 爬虫、Open GEO 自测、其他自动化请求和身份验证证据。" },
  },
  source: "Cloudflare Worker + D1",
  backToSite: "返回网站",
  ranges: { "24h": "24h", "7d": "7d", "30d": "30d" },
  automationTotal: "自动化请求",
  human: {
    title: "人类浏览器访问",
    pageViews: "页面访问",
    paths: "人类访问热门页面",
    peakPeriods: "人类访问高峰时段",
    activePeriods: "有访问时段",
    peakPageViews: "单时段峰值",
    status: "页面状态码",
    devices: "访问设备",
    browsers: "访问浏览器",
    operatingSystems: "操作系统",
    countries: "国家/地区",
    regions: "省/州",
    unknownLocation: "未知",
    locationDisclaimer: "地区来自 Cloudflare 对请求来源的粗粒度判断，只统计国家/地区和一级行政区，不保存城市、经纬度或 IP。",
    noClientData: "设备与浏览器分类将在新版记录器开始采集后显示。",
    deviceLabels: { desktop: "桌面设备", mobile: "手机", tablet: "平板", other: "其他设备" },
    browserLabels: { chrome: "Chrome", safari: "Safari", edge: "Edge", firefox: "Firefox", wechat: "微信内置浏览器", samsung_internet: "Samsung Internet", other: "其他浏览器" },
    operatingSystemLabels: { windows: "Windows", macos: "macOS", ios: "iOS", android: "Android", linux: "Linux", chromeos: "ChromeOS", other: "其他系统" },
    disclaimer: "按疑似人类浏览器的 HTML 页面请求计数，不使用 Cookie，也不是独立访客数。自动化程序伪装浏览器时仍可能被计入。",
    trackingStartedAt: "人类访问统计从",
    incompleteWindow: "开始；此前没有可回填的历史数据。",
  },
  share: "占比",
  queryWindow: "查询窗口",
  lastRefresh: "最后刷新",
  categories: {
    identified_ai_crawler: "声明的 AI 爬虫",
    open_geo_self_test: "Open GEO 自测",
    other_automation: "其他自动化",
  },
  trend: "自动化请求趋势",
  trendData: "自动化请求趋势数据",
  legend: "趋势图例",
  activePeriods: "有流量时段",
  peakRequests: "单时段峰值",
  peakTime: "峰值时间",
  peakPeriods: "流量最高的时段",
  peakPeriodsHelp: "仅展示前 6 个，零流量时段不再逐行列出。",
  noPeak: "暂无",
  time: "时间",
  bots: "爬虫",
  paths: "热门路径",
  statuses: "状态码分布",
  generatedAt: "生成时间",
  category: "分类",
  requests: "请求数",
  path: "路径",
  status: "状态码",
  total: "合计",
  emptyTrend: "所选时间内没有可绘制的自动化趋势。",
  empty: "所选时间内未识别到自动化流量；这不代表不存在未声明身份的爬虫。",
  incompleteWindow: "记录器初始化前无历史，当前只展示初始化后数据。",
  bestEffort: "统计为尽力而为的记录器数据。",
  identityDisclaimer: "AI 普通 User-Agent 仅归为声明的 AI 爬虫；只有有效签名的 Open GEO 请求才属于自测，未签名请求由记录器归入其他自动化或忽略。",
  identityPreview: {
    title: "V2 身份验证预览",
    description: "影子模式不会改变当前正式统计；验证结果仅用于 7 天观察。",
    total: "V2 自动化请求",
    statuses: {
      verified_official: "官方可信",
      declared_unverified: "仅声明身份",
      suspected_spoof: "疑似伪装",
      other_automation: "其他自动化",
    },
    methods: {
      official_ip_range: "官方 IP 范围",
      signed_hmac: "签名验证",
      ua_only: "User-Agent 声明",
      generic_bot: "通用自动化识别",
    },
    rules: {
      fresh: "规则今天同步成功",
      last_known_good: "正在使用最近有效规则",
      unavailable: "官方规则当前不可用",
    },
    ruleUpdatedAt: "规则最近更新时间",
    neverSynced: "尚无成功同步",
    ruleSources: {
      openai_gptbot: "OpenAI GPTBot",
      openai_searchbot: "OpenAI OAI-SearchBot",
      openai_chatgpt_user: "OpenAI ChatGPT-User",
      perplexity_bot: "PerplexityBot",
      perplexity_user: "Perplexity-User",
    },
  },
  errors: {
    configuration_missing: "爬虫检测尚未配置 Worker 读取密钥。",
    observer_auth_invalid: "Crawler Observer 读取签名无效。",
    observer_unavailable: "Crawler Observer 当前不可用。",
    invalid_range: "时间范围无效，请选择 24 小时、7 天或 30 天。",
  } satisfies Record<CrawlerAnalyticsErrorCode, string>,
} as const;
