import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CheckCircle2 } from "lucide-react";

import { getLocalizedPublicContent } from "@/config/public-content";

export const metadata: Metadata = { title: "关于", description: "企业 AI 自动化系统设计与交付：从流程诊断、人机边界到真实验收。", alternates: { canonical: "/about" } };

export default function AboutPage() {
  const content = getLocalizedPublicContent("zh");
  return <div className="min-h-screen bg-surface-paper pb-20 pt-28 text-surface-paper-foreground sm:pt-32"><div className="mx-auto max-w-6xl px-4"><header className="max-w-4xl"><p className="font-mono text-xs font-semibold uppercase tracking-[0.18em] text-accent">About the work</p><h1 className="mt-4 text-4xl font-semibold leading-tight tracking-[-0.04em] text-foreground sm:text-6xl">我做的不是一个固定行业模板，而是把真实业务流程变成可运行的系统</h1><p className="mt-6 text-lg leading-9 text-muted-foreground">{content.identity.description}</p></header><div className="mt-14 grid gap-12 border-y border-hairline py-12 lg:grid-cols-2"><section><h2 className="text-2xl font-semibold text-foreground">适合处理的问题</h2><ul className="mt-6 space-y-4">{content.service.suitableWork.map((item) => <li key={item} className="flex gap-3 text-sm leading-7 text-muted-foreground"><CheckCircle2 className="mt-1 h-4 w-4 flex-none text-accent" aria-hidden />{item}</li>)}</ul></section><section><h2 className="text-2xl font-semibold text-foreground">不会模糊的边界</h2><ul className="mt-6 space-y-4">{content.service.boundaries.map((item) => <li key={item} className="flex gap-3 text-sm leading-7 text-muted-foreground"><CheckCircle2 className="mt-1 h-4 w-4 flex-none text-accent" aria-hidden />{item}</li>)}</ul></section></div><section className="mt-14 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{content.service.method.map((step, index) => <article key={step.id} className="border-t-2 border-accent pt-5"><span className="font-mono text-xs text-muted-foreground">0{index + 1}</span><h2 className="mt-3 text-lg font-semibold text-foreground">{step.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{step.description}</p></article>)}</section><div className="mt-16 bg-surface-graphite p-8 text-surface-graphite-foreground"><h2 className="text-3xl font-semibold">先从一个具体流程问题开始</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-surface-graphite-foreground/70">提交当前流程、频率和人工投入。我会先判断是否适合改造，再决定是否进入初步诊断。</p><Link href="/contact" className="mt-6 inline-flex items-center gap-2 bg-accent px-5 py-3 text-sm font-semibold text-accent-foreground">提交流程问题<ArrowRight className="h-4 w-4" aria-hidden /></Link></div></div></div>;
}
