import type { CustomerStory } from "./cases";
import { caseSceneAccents } from "./caseTheme";

export const caseStories: Record<string, CustomerStory> = {
  "hermes-notebook": {
    archetype: "knowledge-system",
    headline: "把分散资料变成可追溯知识库",
    chapterTitle: "资料到知识卡片",
    shortPromise: "把 PDF、网页和会议记录整理成可追问、可引用、可沉淀的知识。",
    animationSrc: "/animations/projects/hermes/index.html",
    sceneAccent: caseSceneAccents.knowledge,
    publicScenario:
      "团队资料常常散落在 PDF、网页、会议记录、课程字幕和个人笔记里。这个系统把它们整理成可以追问、引用和沉淀的知识工作流。",
    exampleInput: "产品手册 PDF、网页资料、会议纪要、课程字幕",
    transferableValue:
      "适用于培训资料、研究文档、项目交接、内部知识库和长期内容沉淀。",
    artifactLabel: "可追溯知识卡片",
    proofPoints: [
      "回答保留来源引用",
      "输出可以沉淀为结构化笔记",
      "资料来源、段落位置和检索痕迹可回查",
    ],
    steps: [
      {
        title: "资料导入",
        customerAction: "选择一组资料，让系统统一处理。",
        systemAction: "识别 PDF、网页、文本和字幕，把它们归一化为来源记录。",
        visibleOutput: "不同格式的资料进入同一条知识工作流。",
        artifactPreview: "Source bundle: PDF x1 / webpage x2 / meeting note x1 / transcript x1",
        metric: "source coverage 100%",
        proof: "文件名、来源类型和段落位置会被保留，后续回答可以回到原文。",
      },
      {
        title: "语义整理",
        customerAction: "等待系统把内容拆成可检索知识块。",
        systemAction: "按语义边界切块，记录来源偏移，并建立检索索引。",
        visibleOutput: "资料被整理成可追踪的知识节点，而不是一段不可复查的总结。",
        artifactPreview: "Knowledge nodes: 86 chunks / avg 420 chars / source offsets kept",
        metric: "86 traceable nodes",
        proof: "每个知识块都有来源指针，减少回答脱离资料的问题。",
      },
      {
        title: "带引用问答",
        customerAction: "提出一个业务问题，例如“这组资料里的关键方法是什么？”",
        systemAction: "检索相关片段、排序证据，再生成带引用的回答。",
        visibleOutput: "回答旁边显示可回看的来源，而不是只给一段 AI 文案。",
        artifactPreview: "Answer draft with 5 cited snippets and source labels",
        metric: "top evidence 5",
        proof: "回答和引用一起生成，便于审核、修改和追责。",
      },
      {
        title: "知识沉淀",
        customerAction: "确认回答后，把结果保存成可继续编辑的知识笔记。",
        systemAction: "生成结构化笔记、引用列表和检索 trace。",
        visibleOutput: "得到一张可以放进知识库的卡片，而不是一次性聊天记录。",
        artifactPreview: "Obsidian note + citation list + rag-trace.json",
        metric: "artifact ready",
        proof: "输出物可以继续被检索、引用和复用。",
      },
    ],
  },
  "freight-lead-agent": {
    archetype: "lead-discovery",
    headline: "把公开信息变成可审计线索批次",
    chapterTitle: "公开信息到线索清单",
    shortPromise: "把市场、画像和关键词转成带证据链的优先级名单。",
    animationSrc: "/animations/projects/freight/index.html",
    sceneAccent: caseSceneAccents.leadDiscovery,
    publicScenario:
      "B2B 团队需要从公开网络发现、验证、优先级排序潜在客户。这个系统把搜索、页面理解、证据整理和触达准备串成一条可审核流程。",
    exampleInput: "目标市场、客户画像、关键词组合、地区范围",
    transferableValue:
      "适用于 B2B 销售、渠道拓展、供应商发现、市场调研和名单清洗。",
    artifactLabel: "可审计线索表",
    proofPoints: [
      "每条线索带来源证据",
      "触达动作保留人工确认门槛",
      "评分依据和下一步动作可复核",
    ],
    steps: [
      {
        title: "公开来源发现",
        customerAction: "输入目标市场和客户画像。",
        systemAction: "把关键词拆成多个查询组合，从公开页面和地图类来源收集候选。",
        visibleOutput: "系统得到一批候选公司，并保留它们来自哪个公开来源。",
        artifactPreview: "Candidate batch: 320 public records / 16 source groups",
        metric: "320 candidates",
        proof: "原始来源先入库，后续筛选可以回查。",
      },
      {
        title: "页面理解",
        customerAction: "选择需要进一步验证的候选批次。",
        systemAction: "访问官网、关于页、联系页和公开介绍，提取业务相关证据。",
        visibleOutput: "候选不再只是名字，而是带有业务描述、地区和页面证据。",
        artifactPreview: "Evidence: website summary / contact page / business keywords",
        metric: "184 sites parsed",
        proof: "页面解析结果和原始 URL 一起保存，便于人工复核。",
      },
      {
        title: "线索评分",
        customerAction: "设定优先级规则，例如地区匹配、服务匹配、联系方式完整度。",
        systemAction: "去重、评分、标记证据强弱，并把无效线索排到后面。",
        visibleOutput: "客户看到 A/B/C 线索批次，而不是一堆未整理网页。",
        artifactPreview: "Lead table: priority / evidence / contact readiness / next action",
        metric: "72 reachable leads",
        proof: "评分依据可见，线索不是黑箱排序。",
      },
      {
        title: "触达准备",
        customerAction: "查看推荐动作，决定哪些线索进入测试触达或人工跟进。",
        systemAction: "生成触达计划、测试邮箱预览和审计记录，真实发送前保留确认。",
        visibleOutput: "得到一份可执行的下一步计划，而不是自动乱发邮件。",
        artifactPreview: "Review queue / test mailbox / audit log / owner note",
        metric: "send gated",
        proof: "真实触达前保留人工确认，适合交付给业务团队使用。",
      },
    ],
  },
  "element-asset-sdk": {
    archetype: "ui-asset-runtime",
    headline: "把一次 UI 操作变成可复用资产",
    chapterTitle: "界面操作到 UI 资产",
    shortPromise: "把按钮、表格或导出入口封装成 Agent 可以稳定调用的能力。",
    animationSrc: "/animations/projects/element-sdk/index.html",
    sceneAccent: caseSceneAccents.assetRuntime,
    publicScenario:
      "Agent 或自动化系统要稳定操作网页和桌面软件，不能每次临时猜按钮。这个系统把界面元素封装成可保存、可验证、可复放的操作资产。",
    exampleInput: "一个按钮、表格、表单字段或导出入口",
    transferableValue:
      "适用于浏览器自动化、桌面软件操作、数据抽取、内部工具集成和 Agent 执行动作。",
    artifactLabel: "可复用 UI 资产",
    proofPoints: [
      "资产包含 selector、截图和运行时证据",
      "动作执行前会验证可见性和能力边界",
      "同一模型可迁移到网页和桌面环境",
    ],
    steps: [
      {
        title: "捕获元素",
        customerAction: "在界面里点选一个按钮、表格或表单字段。",
        systemAction: "读取 DOM 或桌面 UI 信息，保存 selector、截图和上下文。",
        visibleOutput: "界面元素被保存成一个候选资产，而不是一次性点击记录。",
        artifactPreview: "Asset candidate: export-button / selector / screenshot evidence",
        metric: "confidence 0.94",
        proof: "截图和结构化定位信息一起保存，降低后续漂移风险。",
      },
      {
        title: "验证资产",
        customerAction: "确认这个元素应该具备点击、抽取或填表能力。",
        systemAction: "检查可见性、稳定 selector、运行时适配器和能力边界。",
        visibleOutput: "系统说明这个资产能做什么、不能做什么。",
        artifactPreview: "Capabilities: click / extract / wait-for-result",
        metric: "13 checks passed",
        proof: "资产必须通过验证才进入可复用状态。",
      },
      {
        title: "抽取数据",
        customerAction: "把资产放进一个任务，例如读取表格并提取字段。",
        systemAction: "解析依赖元素，执行抽取规则，生成结构化结果。",
        visibleOutput: "原本只能肉眼看的 UI 内容变成可消费的数据。",
        artifactPreview: "Extracted rows: name / status / amount / updatedAt / source",
        metric: "6 fields mapped",
        proof: "抽取结果附带验证报告，便于排错和审计。",
      },
      {
        title: "复放动作",
        customerAction: "让系统再次执行同一个资产动作，验证它能被 Agent 调用。",
        systemAction: "复放点击或抽取动作，捕获结果面板，并导出 SDK 调用片段。",
        visibleOutput: "得到一段可以交给其他系统调用的资产 API。",
        artifactPreview: "sdk.asset('export-button').click().captureEvidence()",
        metric: "replayable",
        proof: "最终交付的是可复用能力，不是一次演示脚本。",
      },
    ],
  },
};
